# Generated by Django 3.1rc1 on 2020-08-14 17:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_kwcocodataset_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='keypoints',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='line',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=0),
        ),
        migrations.AlterField(
            model_name='polygonsegmentation',
            name='feature',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=0),
        ),
    ]
